
# databases:
#   - name: mysitedb
#     plan: free
#     database: mysql
#     user: mysite

services:
  - type: web
    plan: free
    name: abadas
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn abadas.wsgi:application -k uvicorn.workers.UvicornWorker"
    # envVars:
    #   - key: DATABASE_URL
    #     fromDatabase:
    #       name: mysitedb
    #       property: connectionString
    #   - key: SECRET_KEY
    #     generateValue: true
    #   - key: WEB_CONCURRENCY
    #     value: 4