# Generated by Django 5.1.3 on 2025-09-10 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('items_json', models.CharField(max_length=5000)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('name', models.CharField(max_length=90)),
                ('email', models.CharField(max_length=90)),
                ('address1', models.CharField(max_length=200)),
                ('address2', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=100)),
                ('oid', models.CharField(blank=True, max_length=150)),
                ('amountpaid', models.CharField(blank=True, max_length=500, null=True)),
                ('paymentstatus', models.CharField(blank=True, max_length=20)),
                ('phone', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='orderUpdate',
            fields=[
                ('update_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_id', models.IntegerField(default='')),
                ('update_desc', models.CharField(max_length=5000)),
                ('delivered', models.BooleanField(default=False)),
                ('timestamp', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('product_category', models.CharField(choices=[('drop-shoulders', 'Drop Shoulders'), ('baggy-joggers', 'Baggy Joggers'), ('baggy-shirts', 'Baggy Shirts'), ('cargo-pants', 'Cargo Pants'), ('head-wear', 'Head Wear'), ('baggy-shorts', 'Baggy Shorts')], default='drop-shoulders', max_length=100)),
                ('product_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('product_desc', models.TextField()),
                ('product_color', models.TextField()),
                ('product_size', models.TextField()),
                ('product_image_1', models.ImageField(upload_to='product-images/')),
                ('product_image_2', models.ImageField(upload_to='product-images/')),
                ('product_image_3', models.ImageField(upload_to='product-images/')),
                ('product_image_4', models.ImageField(upload_to='product-images/')),
                ('product_image_5', models.ImageField(upload_to='product-images/')),
                ('latest_arrival', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=3)),
            ],
        ),
    ]
