# Generated by Django 5.1.3 on 2025-09-12 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_remove_order_payment_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payid_proof',
            field=models.ImageField(blank=True, null=True, upload_to='payment-proofs/'),
        ),
    ]
