# Generated by Django 5.1.3 on 2025-09-15 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_order_shipping_cost_order_shipping_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address1',
            field=models.CharField(max_length=200, verbose_name='Address 1'),
        ),
        migrations.AlterField(
            model_name='order',
            name='address2',
            field=models.CharField(max_length=200, verbose_name='Address 2'),
        ),
        migrations.AlterField(
            model_name='order',
            name='amountpaid',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Amount Paid'),
        ),
        migrations.AlterField(
            model_name='order',
            name='city',
            field=models.CharField(max_length=100, verbose_name='Suburb'),
        ),
        migrations.AlterField(
            model_name='order',
            name='email',
            field=models.CharField(max_length=90, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='order',
            name='is_guest_order',
            field=models.BooleanField(default=False, help_text='True if this is a guest order', verbose_name='Guest Order'),
        ),
        migrations.AlterField(
            model_name='order',
            name='name',
            field=models.CharField(max_length=90, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='order',
            name='oid',
            field=models.CharField(blank=True, max_length=150, verbose_name='Order Id'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payid_proof',
            field=models.ImageField(blank=True, null=True, upload_to='payment-proofs/', verbose_name='PayID Proof'),
        ),
        migrations.AlterField(
            model_name='order',
            name='paymentstatus',
            field=models.CharField(blank=True, max_length=20, verbose_name='Payment Status'),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(default='', max_length=100, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Shipping cost applied', max_digits=10, verbose_name='Shipping Cost'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_method',
            field=models.CharField(blank=True, help_text='Selected shipping method', max_length=50, verbose_name='Shipping Method'),
        ),
        migrations.AlterField(
            model_name='order',
            name='state',
            field=models.CharField(max_length=100, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PLACED', 'Placed'), ('CONFIRMED', 'Confirmed'), ('REJECTED', 'Rejected')], default='PLACED', max_length=10, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='order',
            name='zip_code',
            field=models.CharField(max_length=100, verbose_name='Post Code'),
        ),
    ]
