# Generated by Django 5.1.3 on 2025-09-15 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_alter_order_address1_alter_order_address2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Shipping method name (e.g., 'Regular Post', 'Express Post')", max_length=100)),
                ('cost', models.DecimalField(decimal_places=2, help_text='Shipping cost in dollars', max_digits=10)),
                ('description', models.CharField(blank=True, help_text='Optional description for the shipping method', max_length=200)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this shipping option is available')),
                ('is_default', models.BooleanField(default=False, help_text='Whether this is the default selected option')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Order in which options appear (lower numbers first)')),
            ],
            options={
                'verbose_name': 'Shipping Option',
                'verbose_name_plural': 'Shipping Options',
                'ordering': ['sort_order', 'name'],
            },
        ),
    ]
