# Generated by Django 5.1.3 on 2025-09-16 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_productstock'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductStock',
        ),
    ]
