# Generated by Django 5.1.3 on 2025-09-16 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_delete_productstock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_color',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_size',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.CreateModel(
            name='ProductStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=20)),
                ('color', models.CharField(max_length=30)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='shop.product')),
            ],
            options={
                'verbose_name': 'Product Stock',
                'verbose_name_plural': 'Product Stock',
                'unique_together': {('product', 'size', 'color')},
            },
        ),
    ]
