# Generated by Django 5.1.3 on 2025-09-19 05:25

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_alter_product_product_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_desc',
            field=tinymce.models.HTMLField(),
        ),
    ]
